### ISSUE TITLE
Types need to be overhauled

### ISSUE THREAD

**Issue by jackHedaya** [safebash/opencrypto#21]
Though the methods are offered in TypeScript, the parameters and return types are missing type signatures. I'm currently working on a PR but am probably going to need some help with certain parameters.

**Comment by PeterBielak** [comment]
Hi @jackHedaya, thank you very much for the contribution, it is very appreciated! Feel free to let me know if you have any and all questions.

**Comment by jackHedaya** [comment]
Think it's all good, managed by reading the lib code. PR should be ready to merge!
