### ISSUE TITLE
encrypt / decrypt are missing padding functionality

### ISSUE THREAD

**Issue by Korkman** [safebash/opencrypto#3]
Must pad to 4 bytes before crypt (for default settings), otherwise decrypt will corrupt the data

Edit: which is weird, because the default AES-GCM should not require padding ...

Testing in Firefox and Chrome

**Comment by Korkman** [comment]
Here's a Codepen demonstrating:

https://codepen.io/anon/pen/jdqQRe

**Comment by PeterBielak** [comment]
Hi @Korkman thanks for reporting the issue. Data input for encrypt() method needs to be base64 encoded. See below:

const text = '123456'
const encoded = oc.arrayBufferToBase64(oc.stringToArrayBuffer(text))

This functionality may change to accept ArrayBuffer on default as a new version will be released shortly.

Please let me know if you have any further questions.

**Comment by Korkman** [comment]
Thank you for clearing this up! Updated the Codepen, works as expected now.

**Comment by PeterBielak** [comment]
@Korkman You're welcome! I'm glad that everything works on your end, still don't hesitate to let me know if you find any further issues.
