### ISSUE TITLE
Encrypt & sign data?

### ISSUE THREAD

**Issue by pwFoo** [safebash/opencrypto#6]
Encrypted Data is base64 and so can't be used direct with sign function which needs ArrayBuffer input.

How should I sign+encrypt data? 
First sign plain data, then encrypt the data and send encrypted data + signature to the recipient? 
The recipient have to decrypt first to verify the signature with the plain data in second step?

**Comment by PeterBielak** [comment]
Hi there, thank you for reporting the issue.

In general you should sign the plain data first and then encrypt both the data and the signature which you can then send to the recipient.

OpenCrypto includes several methods which can be used to encode and represent data in multiple encoding schemes.

```
const crypt = new OpenCrypto()
const base64 = 'some base64 encoded data'
const arrayBuffer = crypt.base64ToArrayBuffer(base64)
```

Feel free to let me know if you need any further assistance and thank you for your interest in OpenCrypto.

Best Regards,
Peter Bielak

**Comment by pwFoo** [comment]
Hi, how to encrypt both together? Save in array or object structure, convert to base64 + arrayBuffer and then encrypt?

**Comment by PeterBielak** [comment]
Hi there, I'm sorry for the delay.

You may either sign the data with one of the asymmetric algorithms such as RSA-PSS, ECDSA or consider using MAC (Message Authentication Code).

The way you append signature and deliver the data to the recipient depends on your specific case.

There is also AES-GCM, which is an authenticated encryption algorithm that provides both data integrity and confidentiality.
