### ISSUE TITLE
feature-request:  retrieve public-key from private-key(pem)

### ISSUE THREAD

**Issue by alpastar** [safebash/opencrypto#7]
get, or create RSA key-pair and convert  cryptoKey(private) to pem 

from this pem(private), can i retrieve public key ? 
if not , what  about add such method ...

**Comment by PeterBielak** [comment]
Hi there, thank you for the suggestion. It is very appreciated!

I just published a new version v1.5.3, which includes support for public key retrieval using the `getPublicKey` method.

Please see the code below as a reference on how you can retrieve a public key from an RSA-OAEP, RSA-PSS, ECDH, or ECDSA private key.

```javascript
const keyPair = await crypt.getRSAKeyPair()
console.log(keyPair)

const pemPrivateKey = await crypt.cryptoPrivateToPem(keyPair.privateKey)
console.log(pemPrivateKey)

const cryptoPrivateKey = await crypt.pemPrivateToCrypto(pemPrivateKey)
console.log(cryptoPrivateKey)

const publicKey = await crypt.getPublicKey(cryptoPrivateKey)
console.log(publicKey)
```

Feel free to let me know if you need any further help.

Best Regards,
Peter Bielak
