### ISSUE TITLE
Getting started with asymmetric encryptions/decryptions

### ISSUE THREAD

**Issue by bpolaszek** [safebash/opencrypto#9]
Hey there! I'm trying to achieve something that looks simple, but don't manage to figure out why it doesn't work.

Scenario is: 
- Client generates key pair
- Client asks a resource to the back-end, with a "hey encrypt it with that public key"
- Client decrypts back-end's payload with the private key.

On the client side:
```js
const crypt = new OpenCrypto();
const keyPair = await crypt.getRSAKeyPair();
const publicKey = keyPair.publicKey;
const privateKey = keyPair.privateKey;
const publicPem = await crypt.cryptoPublicToPem(publicKey);
```

Consider calling the back-end which returns `foobar`, encrypted with `publicPem` and base64-encoded:
```php
# PHP Back-end (simplified)
$publicKeyPem = file_get_contents('php://input');
$publicKey = \openssl_pkey_get_public($publicKeyPem);
\openssl_public_encrypt('foobar', $encryptedData, $publicKey, \OPENSSL_PKCS1_OAEP_PADDING);
\openssl_free_key($publicKey);
echo \base64_encode($encryptedData);
```

Produces:
```
wmjQ5u5DViF4yeanx7ncmyZ0ekY0jNQd/f4SC+1AzGsSXzARArpyp+4Blv+Q3tR4oqdriRcxa8OQpSbfrfp4gZKqssobdMMxJd0Cr3xTCtzRX7sn+t+JnX4FwYepEdmqEYyWDsKuiA5eFs89PrdHqJzIADeOiElHQoi4B4flEDj124ydpLPcmLh3UIsNZAz3n73QAQmhRvvFyW8FmQ+IGEhHD/HSizn959cYqpi9gPx4uACdeO16okK2s9Z4kIQi+cf8dg6iAXA4z10d4hfhRyLqwtFhaZQdq2cQUJg41Hqh177N3dLW0CwU6t4aMizovkYtI7xIFvOCmHSzlDISWg==
```

Now, getting that string in a `payload` JS var:
```js
const decrypted = crypt.arrayBufferToString(await crypt.rsaDecrypt(privateKey, payload));
```

Produces a DOMException (?).

2 things to note:
- If I also POST the private key to the back-end side, PHP is able to perform both encryption and decryption.
- If I don't use the back end and just perform a `foobar` encryption/decryption on the client side, it works.

It just don't work when something external to OpenCrypto is encrypting something, even with OpenCrypto's generated keys.

Any ideas? Or maybe am I using the wrong algorithm (RSA is well supported on the PHP side)?

Thank you,
Ben

**Comment by PeterBielak** [comment]
Hi @bpolaszek, thank you for your interest in OpenCrypto, and apologies for the delay.

I researched your issue thoroughly and found out what has been causing it.

The problem is that OpenSSL in PHP has SHA-1 hash function set as default for encryption with RSA in `openssl_public_encrypt`. On the other hand, OpenCrypto uses SHA-512 as a default hash function. These hash functions must match in both environments. Therefore you need to update your client-side code accordingly.

```
// Working solution with changes to OpenCrypto
const crypt = new OpenCrypto()
const keyPair = await crypt.getRSAKeyPair(2048, 'SHA-1')
const publicKey = keyPair.publicKey
const privateKey = keyPair.privateKey
const publicPem = await crypt.cryptoPublicToPem(publicKey)

# PHP Back-end (simplified)
$publicKeyPem = file_get_contents('php://input');
$publicKey = \openssl_pkey_get_public($publicKeyPem);
\openssl_public_encrypt('foobar', $encryptedData, $publicKey, \OPENSSL_PKCS1_OAEP_PADDING);
\openssl_free_key($publicKey);
echo \base64_encode($encryptedData);
```

I tested this solution, and it has successfully solved the DOMException error.

Feel free to let me know if you need further assistance or have any more questions.

Have a great day!

**Comment by bpolaszek** [comment]
Hello @PeterBielak,

Sorry for getting back so late! I tested your solution and it works. 
Thanks a lot for the tip!
